site_name: داده‌ساختارها و الگوریتم‌ها
site_description: صفحه درس داده‌ساختارها و الگوریتم‌ها
site_url: https://amirrezabb.github.io/UoH-DSA-14051/


docs_dir: docs


theme:
  name: material
  language: fa
  direction: rtl
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: حالت روشن
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: حالت تاریک


nav:
  - خانه: index.md
  - تمرینات: exercises.md


plugins:
  - search:
      lang:
        - fa



extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html